import os
from datetime import datetime
from config import UPLOAD_DIR


def generate_docx(results: dict, file_id: str) -> str:
    """
    Generate a .docx file from the optimized resume and cover letter.
    Returns the file path.
    """
    from docx import Document
    from docx.shared import Pt, Inches, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()

    # Set default font
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Calibri"
    font.size = Pt(11)

    # Title
    title = doc.add_heading("ATS-Optimized Resume", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph(f"Generated by ResumeAI — {datetime.now().strftime('%B %d, %Y')}")
    doc.add_paragraph("_" * 50)

    # Add optimized resume
    optimized = results.get("optimized_resume", "")
    if optimized:
        doc.add_heading("Optimized Resume", level=1)
        # Split by lines and add
        for line in optimized.split("\n"):
            line = line.strip()
            if not line:
                continue
            if line.startswith("# "):
                doc.add_heading(line[2:], level=1)
            elif line.startswith("## "):
                doc.add_heading(line[3:], level=2)
            elif line.startswith("### "):
                doc.add_heading(line[4:], level=3)
            elif line.startswith("- "):
                doc.add_paragraph(line[2:], style="List Bullet")
            elif line.startswith("**") and line.endswith("**"):
                p = doc.add_paragraph()
                run = p.add_run(line.strip("*"))
                run.bold = True
            else:
                doc.add_paragraph(line)

    # Add cover letter if present
    cover_letter = results.get("cover_letter", "")
    if cover_letter:
        doc.add_page_break()
        doc.add_heading("Cover Letter", level=1)
        for line in cover_letter.split("\n"):
            line = line.strip()
            if not line:
                continue
            if line.startswith("# "):
                doc.add_heading(line[2:], level=1)
            elif line.startswith("## "):
                doc.add_heading(line[3:], level=2)
            else:
                doc.add_paragraph(line)

    # Save
    docx_path = os.path.join(UPLOAD_DIR, f"{file_id}_resume.docx")
    doc.save(docx_path)
    return docx_path


def generate_pdf(results: dict, file_id: str) -> str:
    """
    Generate a PDF from the optimized resume.
    """
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable

    pdf_path = os.path.join(UPLOAD_DIR, f"{file_id}_resume.pdf")
    doc = SimpleDocTemplate(pdf_path, pagesize=letter, topMargin=0.75*inch, bottomMargin=0.75*inch)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = ParagraphStyle(
        "CustomTitle", parent=styles["Title"], fontSize=24, spaceAfter=12
    )
    story.append(Paragraph("ATS-Optimized Resume", title_style))
    story.append(Paragraph(f"Generated by ResumeAI — {datetime.now().strftime('%B %d, %Y')}", styles["Normal"]))
    story.append(Spacer(1, 12))
    story.append(HRFlowable(width="100%", thickness=1))

    # Optimized resume
    optimized = results.get("optimized_resume", "")
    if optimized:
        story.append(Spacer(1, 12))
        for line in optimized.split("\n"):
            line = line.strip()
            if not line:
                story.append(Spacer(1, 6))
                continue
            if line.startswith("# "):
                story.append(Paragraph(line[2:], styles["Heading1"]))
            elif line.startswith("## "):
                story.append(Paragraph(line[3:], styles["Heading2"]))
            elif line.startswith("### "):
                story.append(Paragraph(line[4:], styles["Heading3"]))
            elif line.startswith("- "):
                story.append(Paragraph(f"• {line[2:]}", styles["Normal"]))
            else:
                story.append(Paragraph(line, styles["Normal"]))

    # Cover letter
    cover_letter = results.get("cover_letter", "")
    if cover_letter:
        story.append(Spacer(1, 24))
        story.append(HRFlowable(width="100%", thickness=1))
        story.append(Paragraph("Cover Letter", styles["Heading1"]))
        for line in cover_letter.split("\n"):
            line = line.strip()
            if not line:
                story.append(Spacer(1, 6))
                continue
            story.append(Paragraph(line, styles["Normal"]))

    doc.build(story)
    return pdf_path